# Generated by Django 6.0.5 on 2026-08-29 13:58

import django.db.models.deletion
import django.utils.timezone
import luxury_fashion.apps.accounts.models.client_model
import luxury_fashion.apps.core.validators.image_validator
import luxury_fashion.apps.core.validators.validate_cep
import luxury_fashion.apps.core.validators.validate_cpf_or_cnpj
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='JTI do token')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Metadado de sessão',
                'verbose_name_plural': 'Metadados de sessão',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Administrador Root'), ('client', 'Cliente')], default='client', max_length=20, verbose_name='Tipo de usuário')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo?')),
                ('is_trusty', models.BooleanField(default=False, verbose_name='Confiável?')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de admissão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sobrenome')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Nome de usuário')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', help_text='Número de telefone no formato internacional, ex: +55 11 99999-8888.', max_length=128, null=True, region='BR')),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], default='Outro', max_length=10, verbose_name='Gênero')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('photo', models.ImageField(blank=True, default='default/client_img.jpg', help_text='Formatos aceitos: jpg, jpeg ou png. Máx: 5MB.', null=True, upload_to=luxury_fashion.apps.accounts.models.client_model.client_photo_path, validators=[luxury_fashion.apps.core.validators.image_validator.validate_image_file])),
                ('asaas_customer_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='ID do cliente na Asaas')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, validators=[luxury_fashion.apps.core.validators.validate_cpf_or_cnpj.validate_cpf], verbose_name='CPF')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='AddressesClient',
            fields=[
                ('address_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=9, validators=[luxury_fashion.apps.core.validators.validate_cep.validate_cep], verbose_name='CEP')),
                ('street', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='Bairro')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('country', models.CharField(default='Brasil', max_length=100, verbose_name='País')),
                ('is_preferential', models.BooleanField(default=True, verbose_name='Preferencial')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.client')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['first_name', 'last_name'], name='accounts_cl_first_n_7eb737_idx'),
        ),
        migrations.AddIndex(
            model_name='addressesclient',
            index=models.Index(fields=['state', 'city'], name='accounts_ad_state_f9f24a_idx'),
        ),
        migrations.AddIndex(
            model_name='addressesclient',
            index=models.Index(fields=['city'], name='accounts_ad_city_c33c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='addressesclient',
            index=models.Index(fields=['street', 'city'], name='accounts_ad_street_6c476e_idx'),
        ),
        migrations.AddIndex(
            model_name='addressesclient',
            index=models.Index(fields=['neighborhood', 'city'], name='accounts_ad_neighbo_4b3e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='addressesclient',
            index=models.Index(fields=['cep'], name='accounts_ad_cep_1bdc4e_idx'),
        ),
    ]
