# Generated by Django 6.0.5 on 2026-09-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='asaas_customer_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cpf',
        ),
        migrations.AddField(
            model_name='client',
            name='cpf_encrypted',
            field=models.TextField(blank=True, null=True, verbose_name='CPF (criptografado)'),
        ),
        migrations.AddField(
            model_name='client',
            name='cpf_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Hash do CPF'),
        ),
    ]
