# Generated by Django 6.0.5 on 2026-09-11 19:02

import django.db.models.deletion
import luxury_fashion.apps.accounts.models.admin_model
import luxury_fashion.apps.core.validators.image_validator
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_client_asaas_customer_id_remove_client_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('admin_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('photo', models.ImageField(blank=True, default='default/admin_img.jpg', help_text='Formatos aceitos: jpg, jpeg ou png. Máx: 5MB.', null=True, upload_to=luxury_fashion.apps.accounts.models.admin_model.admin_photo_path, validators=[luxury_fashion.apps.core.validators.image_validator.validate_image_file])),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Administrador',
                'verbose_name_plural': 'Perfis dos Administradores',
                'ordering': ['full_name'],
            },
        ),
    ]
