# Generated by Django 6.0.5 on 2026-09-10 23:36

import django.core.validators
import django.db.models.deletion
import luxury_fashion.apps.core.validators.image_validator
import luxury_fashion.apps.website.models.campaignImage_model
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo?')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Início da campanha')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim da campanha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='website_cam_is_acti_7b218c_idx'), models.Index(fields=['starts_at', 'ends_at'], name='website_cam_starts__1b984d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('subject', models.CharField(verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator(message='Digite um e-mail válido')], verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('status', models.TextField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('resolved', 'Resolvido'), ('archived', 'Arquivado')], default='pending', verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['full_name'], name='website_con_full_na_e78ea8_idx'), models.Index(fields=['status'], name='website_con_status_1dc9a3_idx'), models.Index(fields=['created_at'], name='website_con_created_b36bc0_idx'), models.Index(fields=['email'], name='website_con_email_a16188_idx')],
                'constraints': [models.UniqueConstraint(fields=('full_name',), name='unique_contact_name')],
            },
        ),
        migrations.CreateModel(
            name='CampaignImage',
            fields=[
                ('campaign_mage_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=luxury_fashion.apps.website.models.campaignImage_model.campaign_image_path, validators=[luxury_fashion.apps.core.validators.image_validator.validate_image_file], verbose_name='Banner')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Imagem principal')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.campaign')),
            ],
            options={
                'verbose_name': 'Imagem da Campanha',
                'verbose_name_plural': 'Imagens das Campanhas',
                'ordering': ['display_order', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('campaign_id',), name='unique_cover_image_per_campaign')],
            },
        ),
    ]
