# Generated by Django 6.0.5 on 2026-08-29 19:24

import django.core.validators
import django.db.models.deletion
import luxury_fashion.apps.core.validators.image_validator
import luxury_fashion.apps.products.models.product_category_model
import luxury_fashion.apps.products.models.product_image_model
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('product_category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('category_image', models.ImageField(blank=True, default='default/category_img.jpg', help_text='Formatos aceitos: jpg, jpeg ou png. Máx: 5MB.', null=True, upload_to=luxury_fashion.apps.products.models.product_category_model.category_image_path, validators=[luxury_fashion.apps.core.validators.image_validator.validate_image_file])),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produtos',
                'ordering': ['category_name'],
                'constraints': [models.UniqueConstraint(fields=('category_name',), name='unique_category_name')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('product_category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_category', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_image', models.ImageField(upload_to=luxury_fashion.apps.products.models.product_image_model.product_image_path, validators=[luxury_fashion.apps.core.validators.image_validator.validate_image_file], verbose_name='Imagem')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Imagem principal')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Imagem do produto',
                'verbose_name_plural': 'Imagens dos produtos',
                'ordering': ['display_order', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('product_id',), name='unique_cover_image_per_product')],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('variant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(blank=True, choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XGG', 'XGG'), ('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3'), ('G4', 'G4'), ('G5', 'G5'), ('G6', 'G6'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54'), ('56', '56'), ('58', '58'), ('60', '60'), ('62', '62'), ('64', '64')], max_length=5, null=True, verbose_name='Tamanho')),
                ('color', models.CharField(blank=True, choices=[('black', 'Preto'), ('white', 'Branco'), ('red', 'Vermelho'), ('blue', 'Azul'), ('green', 'Verde'), ('pink', 'Rosa'), ('yellow', 'Amarelo'), ('orange', 'Laranja'), ('purple', 'Roxo'), ('brown', 'Marrom'), ('beige', 'Bege'), ('gray', 'Cinza'), ('navy', 'Azul-marinho'), ('wine', 'Vinho'), ('off_white', 'Off-White')], max_length=20, null=True, verbose_name='Cor')),
                ('gender', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('unissex', 'Unissex')], max_length=20, null=True, verbose_name='Gênero')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='O preço não pode ser negativo')], verbose_name='Preço')),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='O estoque não pode ser negativo')], verbose_name='Estoque')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Variante de produto',
                'verbose_name_plural': 'Variantes de produto',
                'ordering': ['product_id', 'size', 'color', 'gender'],
                'constraints': [models.UniqueConstraint(fields=('product_id', 'size', 'color', 'gender'), name='unique_variant_per_product_size_color_gender')],
            },
        ),
    ]
