# Generated by Django 6.0.5 on 2026-08-29 23:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductShipping',
            fields=[
                ('product_shipping_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0.001, message='O peso deve ser maior que zero')], verbose_name='Peso (kg)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.1, message='A altura deve ser maior que zero')], verbose_name='Altura (cm)')),
                ('width', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.1, message='A largura deve ser maior que zero')], verbose_name='Largura (cm)')),
                ('length', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.1, message='O comprimento deve ser maior que zero')], verbose_name='Comprimento (cm)')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantidade padrão de itens desta variante por embalagem, usada como base para a cotação de frete.', validators=[django.core.validators.MinValueValidator(1, message='A quantidade deve ser pelo menos 1')], verbose_name='Quantidade por embalagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('variant_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Dados de frete do produto',
                'verbose_name_plural': 'Dados de frete dos produtos',
            },
        ),
    ]
