# Generated by Django 6.0.5 on 2026-08-30 02:23

import luxury_fashion.apps.core.validators.validate_cep
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productshipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='productshipping',
            name='origin_zip_code',
            field=models.CharField(default='45201347', max_length=11, validators=[luxury_fashion.apps.core.validators.validate_cep.validate_cep], verbose_name='CEP de origem'),
        ),
    ]
