# Generated by Django 6.0.5 on 2026-09-10 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0003_alter_payment_asaas_payment_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviews_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviews', models.PositiveSmallIntegerField(choices=[(1, '⭐ 1 Estrela - Péssimo'), (2, '⭐⭐ 2 Estrelas - Ruim'), (3, '⭐⭐⭐ 3 Estrelas - Regular'), (4, '⭐⭐⭐⭐ 4 Estrelas - Bom'), (5, '⭐⭐⭐⭐⭐ 5 Estrelas - Excelente')], help_text='Nota de 1 a 5 estrelas', verbose_name='Avaliação')),
                ('comment', models.TextField(blank=True, help_text='Deixe um comentário sobre sua experiência', max_length=500, null=True, verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_authorized', models.BooleanField(default=False, verbose_name='Autorizado')),
                ('order_item_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='payments.orderitem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação de serviço',
                'verbose_name_plural': 'Avaliações de serviços',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='reviews_rev_user_id_59d664_idx'), models.Index(fields=['order_item_id'], name='reviews_rev_order_i_acb6bf_idx'), models.Index(fields=['reviews'], name='reviews_rev_reviews_2fa8bd_idx')],
                'constraints': [models.UniqueConstraint(fields=('order_item_id', 'user_id'), name='unique_reviews_per_order_item_id_user_id')],
            },
        ),
    ]
