# Generated by Django 6.0.5 on 2026-09-05 21:09

import django.core.validators
import django.db.models.deletion
import luxury_fashion.apps.core.utils.generate_random_code
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_client_asaas_customer_id_remove_client_cpf_and_more'),
        ('products', '0003_productshipping_origin_zip_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsaasCustomer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asaas_customer_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='ID do cliente na Asaas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asaas_customer', to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=luxury_fashion.apps.core.utils.generate_random_code.generate_random_code, editable=False, max_length=12, unique=True, verbose_name='Código')),
                ('order_status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Completo'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado'), ('FAILED', 'Falhou')], default='PENDING', max_length=15, verbose_name='Status')),
                ('total_geral', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço total')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('order_shipping_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço total de frete')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da compra')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('shipping_address', models.ForeignKey(help_text='Snapshot do endereço no momento da compra.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.addressesclient')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_item_quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('order_item_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço unitário')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.order')),
                ('variant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Item do pedido',
                'verbose_name_plural': 'Itens do pedido',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asaas_payment_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='ID da cobrança no Asaas')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Produto')),
                ('billing_type', models.CharField(choices=[('BOLETO', 'Boleto'), ('PIX', 'Pix'), ('CREDIT_CARD', 'Cartão de Crédito')], db_index=True, default='PIX', max_length=20, verbose_name='Forma de Pagamento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RECEIVED', 'Recebido'), ('CONFIRMED', 'Confirmado'), ('OVERDUE', 'Vencido'), ('REFUNDED', 'Reembolsado'), ('RECEIVED_IN_CASH', 'Recebido em dinheiro'), ('REFUND_REQUESTED', 'Reembolso solicitado'), ('REFUND_IN_PROGRESS', 'Reembolso em andamento'), ('CHARGEBACK_REQUESTED', 'Chargeback solicitado'), ('CHARGEBACK_DISPUTE', 'Disputa de chargeback'), ('AWAITING_CHARGEBACK_REVERSAL', 'Aguardando reversão de chargeback'), ('DUNNING_REQUESTED', 'Negativação solicitada'), ('DUNNING_RECEIVED', 'Negativação recebida'), ('AWAITING_RISK_ANALYSIS', 'Em análise antifraude'), ('CANCELLED', 'Cancelado')], db_index=True, default='PENDING', max_length=30, verbose_name='Status do Pagamento')),
                ('due_date', models.DateField(verbose_name='Data limite para efetuar pagamento')),
                ('description', models.TextField(max_length=500, verbose_name='Descrição da cobrança')),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Referência externa')),
                ('invoice_url', models.URLField(blank=True, null=True, verbose_name='URL da fatura')),
                ('bank_slip_url', models.URLField(blank=True, null=True, verbose_name='URL do boleto')),
                ('pix_qr_code', models.TextField(blank=True, null=True, verbose_name='QR Code Pix')),
                ('pix_copy_paste', models.TextField(blank=True, null=True, verbose_name='Código Pix copia e cola')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('net_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor líquido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('synced_with_asaas', models.BooleanField(default=False, verbose_name='Sincronizado com Asaas')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.order')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['code'], name='payments_or_code_66c34f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status'], name='payments_or_order_s_fc8f07_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='payments_or_created_00c39c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user_id'], name='payments_or_user_id_78ccc9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'due_date'], name='payments_pa_status_0d3455_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order_id', 'status'], name='payments_pa_order_i_97fa28_idx'),
        ),
    ]
