# Generated by Django 6.0.5 on 2026-09-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em'),
        ),
        migrations.AddField(
            model_name='order',
            name='canceled_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo do cancelamento'),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concluído em'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Completo'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado'), ('FAILED', 'Falhou')], default='PENDING', max_length=15, verbose_name='Status'),
        ),
    ]
