# Generated by Django 6.0.5 on 2026-09-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order_canceled_at_order_canceled_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='asaas_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='ID da cobrança no Asaas'),
        ),
    ]
